services:
  bamp:
    image: bamp
    container_name: bamp
    build: .
    sysctls:
      net.ipv4.ip_local_port_range: 10000 65000
    environment: 
      - PULSE_SERVER=127.0.0.1
    volumes:
      - "~/.config/pulse:/var/lib/mopidy/.config/pulse"
      - "../mopidy_bamp:/var/lib/mopidy/mopidy_bamp"
      - "../database:/var/lib/mopidy/database"
      - "../media:/var/lib/mopidy/media"
      - "../cache:/var/lib/mopidy/.cache"
    expose:
      - "6680"
  
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../letsencrypt/etc/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  icecast:
    build: ./icecast
    volumes:
      - ./icecast/logs:/var/log/icecast2
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
    ports:
      - 8000:8000
